### ISSUE TITLE
valid values

### ISSUE THREAD

**Issue by makleso6** [Bouke/HAP#106]
Hi! I Creating plugin for Xiaomi humidifier based on https://github.com/russtone/homebridge-mi-humidifier.
There is a function in https://github.com/russtone/homebridge-mi-humidifier/blob/master/index.js#L64 valid values.
Is there any equivalent in HAP?

**Comment by makleso6** [comment]
also I test in fork
https://github.com/makleso6/HAP/commit/aabce61d33b77032ad1fa6701c47bdec255d3da3

**Comment by makleso6** [comment]
![photo_2020-05-24_21-36-17](https://user-images.githubusercontent.com/9068221/82761951-a268f000-9e06-11ea-904c-8fe7d6d5c632.jpg)

**Comment by makleso6** [comment]
also can implement "valid-values-range"

**Comment by makleso6** [comment]
Add it in pr #107

**Comment by Bouke** [comment]
Thanks for the PR, merged!
