### ISSUE TITLE
Links in README return 404

### ISSUE THREAD

**Issue by spprichard** [Bouke/HAP#109]
When attempting to click the `Get Started` link in the README I get sent to this page

<img width="797" alt="image" src="https://user-images.githubusercontent.com/10872240/88213069-dcdfe500-cc1d-11ea-9ca9-3d813175ce2d.png">

This is true for all links in `Content` section: https://github.com/Bouke/HAP#contents

**Comment by Bouke** [comment]
Thank you for bringing this to my attention. I've been busy setting up docs through Github actions, but need to put in some additional effort.
