### ISSUE TITLE
Project doesn't run on command line

### ISSUE THREAD

**Issue by lorenzofiamingo** [Bouke/HAP#119]
After the `swift run -c release hap-server` command and the QR code scan, HomeKit wasn't able to connect the bridge.
Anyway, I tried with SPM, running the hap-server schema, and it worked.

**Comment by Bouke** [comment]
Can you provide some more information?

**Comment by lorenzofiamingo** [comment]
After the `swift run -c release hap-server` command and the QR code scan, HomeKit wasn't able to connect the bridge.
Anyway, I tried with SPM, running the hap-server schema, and it worked.
