### ISSUE TITLE
Compatibility with Matter

### ISSUE THREAD

**Issue by TheMisfit68** [Bouke/HAP#152]
Any experience with HAP-server and the new Matter protocol?

My HAP-based home automation server runs on a Mac Mini M1 Server with Mac OS Ventura.
When I update the client apps on my iPhone, HomePod and Macbook to use the new Matter-protocol, how
wil this affect my setup?

**Comment by Bouke** [comment]
Hi @TheMisfit68. I don't have experience with Matter. I would be interested to know how it relates to Homekit and the backward compatibility story. Nevertheless I suppose Homekit should continue working. By "client apps" you mean iOS 16? I don't expect Apple to drop Homekit anytime soon, as that would effectively cause those Homekit devices to be useless.

**Comment by TheMisfit68** [comment]
After I first updated my iPone to iOS16 and also
the server running HAP to Mac OS Ventura (both supporting the new style Home-app), 
I was most concerned with updating my HomePod to the latest firmware so it would become "Matter-compatible".

Turns out it all keeps working. 
For now Matter-compatibility is just an extra on top of HomeKit. :D
