### ISSUE TITLE
When internet drops and comes back, app needs to be restarted.

### ISSUE THREAD

**Issue by TwisterMc** [Bouke/HAP#165]
Whenever my internet goes down, once it comes back up, the TPL Bridge no longer works. If I'm in Home and I try to turn on a device, nothing happens. I have to quit TPL Bridge and restart it for the devices work in Home again.

I'd love it if there was a way for it to re-connect without me having to quit the app and start it again.

**Comment by Bouke** [comment]
I'm not sure what "TPL Bridge" is. Is it something that packages this library?

Please note that this is an open source library provided as-is without warranty. Feel free to prod around and see what's causing this issue, and report back your findings.

**Comment by TwisterMc** [comment]
It's been a long time since I wrote that comment, and I don't recall how I got directed here from https://www.brooker.mobi/tpl-bridge/. Since then, I've found different ways of working, so I'll close this.
