### ISSUE TITLE
Verify implementation against official spec

### ISSUE THREAD

**Issue by Bouke** [Bouke/HAP#21]
See the spec which has become available: https://developer.apple.com/homekit/specification/.

**Comment by tgu** [comment]
HAP Spec 2.6.1
> Instance IDs are numbers with a range of [1, 18446744073709551615]. These numbers are used to uniquely identify HAP accessory objects within an HAP accessory server, or uniquely identify services, and characteristics within an HAP accessory object. The instance ID for each object must be unique for the lifetime of the server/ client pairing.

When adding more than eight accessories (independent of type) to a device the Home app will protest on the eight accessory and claim that it is an unsupported accessory. Changing the aid numbering

` accessory.aid = offset == 0 ? 1 : offset+100
`

 will silent the protest. There seems to be more into this than just using unique aid numbering.

**Comment by tgu** [comment]
See 8e83fe071873535dbbfef3cb0d0651e7a01d2a99

**Comment by Bouke** [comment]
I've tried replicating the issue of your [previous comment](https://github.com/Bouke/HAP/issues/21#issuecomment-340350319), but was unable to. On my iPhone (6s / iOS 11.0.3) I'm able to pair with the demo HAP server included with this package. Any idea why you would need the offset, and how this ties into the specs?

**Comment by tgu** [comment]
With the demo HAP server and iPhone (6s/iOS 11.0.3) the results for me are

8e83fe071873535dbbfef3cb0d0651e7a01d2a99 - OK
c6b9a14c7f384e4976bedb003d6dd6b0c283867a - silently refuse to pairing, the Bridge does not show up at all
 9e2df10626eb7f22f3c3150c97061faf8e152f28 - paring is possible but the Toilet window is marked as not supported (Stöds inte, in Swedish)


![img_4764](https://user-images.githubusercontent.com/503551/32211953-3018b932-be15-11e7-8f05-4c1a9ea7b28e.jpg)

**Comment by Bouke** [comment]
Is this still a problem for you?

**Comment by tgu** [comment]
Now it works, thanks!

**Comment by Bouke** [comment]
Most gaps with the specs have been resolved. If any mismatch is found, we can open separate issues.
