### ISSUE TITLE
Building on High Sierra

### ISSUE THREAD

**Issue by Obbut** [Bouke/HAP#25]
Hi there,

Just as a note (maybe include this in the readme?), to build on High Sierra, you need to include some compiler/linker flags:

`swift build -Xswiftc -I/usr/local/opt/libsodium/include -Xlinker -L/usr/local/opt/libsodium/lib`

To generate an Xcode project:

`swift package -Xswiftc -I/usr/local/opt/libsodium/include -Xlinker -L/usr/local/opt/libsodium/lib generate-xcodeproj`

**Comment by Bouke** [comment]
It's strange that you need to specify those flags. SwiftPM should be able to find these files automatically from the pkgconfig files. I just tested on High Sierra / Xcode 9, and it builds/runs just fine without manually specifying them. Can you verify that pkg-config outputs something similar for you?
```
$ pkg-config --cflags libsodium
-I/usr/local/Cellar/libsodium/1.0.11/include
```

**Comment by Obbut** [comment]
Hmm, that's weird, I (and other Vapor users) have to do something similar for openssl on High Sierra since beta 1 and still with the final version.

My `pkg-config` output is similar to yours:

```
$ pkg-config --cflags libsodium
-I/usr/local/Cellar/libsodium/1.0.13/include
```

**Comment by Bouke** [comment]
Would you mind filing a bug at https://bugs.swift.org/ regarding this? SwiftPM should automatically include libsodium because of [this line](https://github.com/Bouke/CLibSodium/blob/bd9df04fd210e445546b3b44767a4574b5f506b7/Package.swift#L5) by inspecting your pkg-config.

**Comment by Obbut** [comment]
Of course, but I'm not really sure anymore if this is indeed a SwiftPM bug. On my other Mac (on which I did not run the developer betas of High Sierra) I do indeed not need to include the paths manually.

Maybe it's just something that's not configured right on my side. I'll try reinstalling some things, and if SwiftPM then doesn't pick up the library, I'll file a bug.

Sorry for bothering you!
