### ISSUE TITLE
Do you have documents to describle HAP?

### ISSUE THREAD

**Issue by ingwii** [Bouke/HAP#3]
As title

**Comment by Bouke** [comment]
What kind of documentation are you looking for? I've build this implementation by looking at other implementations and with lots of trial-and-error.

**Comment by ingwii** [comment]
The other implementations, do you mean the HAP-NodeJS source code? I'm trying to implement this protocol by using C, so that I can run it in embedded system.

**Comment by Bouke** [comment]
There's also https://github.com/brutella/hc, https://github.com/beowulfe/HAP-Java and https://github.com/etwmc/Personal-HomeKit-HAP.

**Comment by ingwii** [comment]
Cool! thanks.
