### ISSUE TITLE
How to handle optional characteristics?

### ISSUE THREAD

**Issue by Bouke** [Bouke/HAP#31]
Take for example the `Info` service, described in 9.1 of the HAP specifications:

> 9.1 Accessory Information
Every accessory must expose a single instance of the Accessory Information service with the following definition. The values of Manufacturer, Model, Name and Serial Number must be persistent through the lifetime of the accessory.
Any other Apple-defined characteristics added to this service must only contain one or more of the following permissions: Paired Read or Notify. Custom characteristics added to this service must only contain one or more of the following permissions: Paired Read, Notify, or Broadcast. All other permissions are not permitted.

Currently it's not worked out how to add custom characteristics. Off course one could create a custom Service, but we need to test that this actually works and is documented.

**Comment by gbrooker** [comment]
Can be closed with PR #73
