### ISSUE TITLE
Linux running issue

### ISSUE THREAD

**Issue by manuduarte** [Bouke/HAP#37]
Hi,

I'm trying to run the project on ubuntu 16.10.0 without success, I already got the message  "Illegal instruction (core dumped)"

**Comment by Bouke** [comment]
That's a rather problematic message, which could result from a lot of situations. What version of Swift are you using? And what version of this package? Try using the latest master of this package and 4.0 of Swift (or even 4.1 master). If that's no go, you could try running the package through `lldb` and record a stack trace of where the illegal instruction is executed.

**Comment by manuduarte** [comment]
I'm using Swift version 4.0.3 (swift-4.0.3-RELEASE) Target: x86_64-unknown-linux-gnu.
Here lldb trace

root@a0270b1d186c:/home/HAP/.build/release# lldb hap-server
(lldb) target create "hap-server"
Current executable set to 'hap-server' (x86_64).
(lldb) r
Process 20454 launched: '/home/HAP/.build/x86_64-unknown-linux/release/hap-server' (x86_64)
Process 20454 stopped
* thread #1, name = 'hap-server', stop reason = signal SIGILL: illegal instruction operand
    frame #0: 0x000000000053ad5a hap-server`NetService.Responder.(in _B4B8C4C6947C16B8992D8E4F6DABB08E).init() throws -> NetService.Responder + 2682
hap-server`NetService.Responder.(in _B4B8C4C6947C16B8992D8E4F6DABB08E).init() throws -> NetService.Responder:
->  0x53ad5a <+2682>: ud2
    0x53ad5c:         nopl   (%rax)
hap-server`NetService.Responder.publish(NetService.NetService) throws -> ():
    0x53ad60 <+0>:    pushq  %rbp
    0x53ad61 <+1>:    movq   %rsp, %rbp
Target 0: (hap-server) stopped.

**Comment by Bouke** [comment]
What's the hostname of the machine you're running this on? Can you show the output of `hostname`?

**Comment by manuduarte** [comment]
This trace is from an Ubuntu docker, the hostname should be a0270b1d186c. I can’t check because I’m travelling until the end of the week. But I also setup a Debian machine with hostname debian.local and I got the same issue.

**Comment by Bouke** [comment]
I don't know what's causing the problem. Try stepping through the code and see what line triggers this crash.

**Comment by Bouke** [comment]
Please reopen if you are still running into this issue and you have more information.
