### ISSUE TITLE
Maintain instance ids assignments between restarts

### ISSUE THREAD

**Issue by Bouke** [Bouke/HAP#49]
From the HAP specification 2.6.1.2:

> After a firmware update services and characteristics types that remain unchanged must retain their previous instance ids, newly added services and characteristics must not reuse instance ids from services and characteristics that were removed in the firmware update.

We currently reassign instance ids.

**Comment by gbrooker** [comment]
This should be fixed with the addition of the persistent configuration

**Comment by Bouke** [comment]
So currently, changing the ordering of services or acessories, would change the instance identifiers. As we already have some persistence in place, I think this can be fixed by extending on that.

**Comment by gbrooker** [comment]
This should be closed now
