### ISSUE TITLE
Possible dependency error in Package.swift

### ISSUE THREAD

**Issue by gbrooker** [Bouke/HAP#54]
I don't build on linux, but spotted this in the linux section of Package.swift
`    package.targets[0].dependencies.append("NetService")
`
Shouldn't that be
`   package.targets[1].dependencies.append("NetService")
`
now that `CQRCode` is the first (i.e [0]) target ?

**Comment by Bouke** [comment]
It worked even though the configuration was not correct. Thanks, I've resolved the issue.
