### ISSUE TITLE
Build Failed on swift 4.2

### ISSUE THREAD

**Issue by manuduarte** [Bouke/HAP#71]
Hi,

I installed swift on an odroid C2 SBC and I'm only able to install swift 4.2.
Building  HAP failed on building BlueSignals

> .build/checkouts/BlueSignals.git-8826455067652766894/Sources/Signals/Signals.swift:111:36:
> 
>  error: converting non-escaping value to 'T' may allow it to escape
>                         sigAction.__sigaction_handler = unsafeBitCast(action, to: sigaction.__Unnamed_union___sigaction_handler.self)
> 

The bug seems to be fixed since [ BlueSIgnals 1.02 ](https://github.com/IBM-Swift/BlueSignals/issues/8) but Kitura-net still use 1.0.0.

After updated BlueSignals to the last release building HAP  on my odroid C2 SBC succes

**Comment by Bouke** [comment]
The next version will drop Kitura and BlueSocket in favor of Nio. You can try https://github.com/Bouke/HAP/pull/68 if you want to give it a go. I’m running that PR myself on a Raspberry Pi and it has been very stable for me.
