### ISSUE TITLE
Upgrade NIO to v2

### ISSUE THREAD

**Issue by Bouke** [Bouke/HAP#91]
NIO released a new major version (v2), which includes some breaking API changes affecting us. This issue tracks the progress of upgrading to v2.

**Comment by ahti** [comment]
fwiw, I did a [quick and dirty port to nio2](https://github.com/ahti/HAP/commit/55ce1265c62b373eedc43c5286f79f7e08903746) a few months ago, which was rather straight-forward. So I don't think it should be much hassle now.

**Comment by gbrooker** [comment]
Is this closed now ?
