### ISSUE TITLE
How to find plugins?

### ISSUE THREAD

**Issue by makleso6** [Bouke/HAP#93]
Hi! Thanks for great project! I really love it.
I'll want write a plugin, but how distribute it and how can people find it?
maybe use prefix **HAP***plugin_name*? Or make Plugins.MD with urls?

**Comment by Bouke** [comment]
Hi @makleso6, thanks! What is this library doing for your use case?

We could start with tagging related projects with the [swift-hap](https://github.com/topics/swift-hap) tag on GitHub. We could add a link to that page in the README once there are more projects listed there. What do you think?

**Comment by makleso6** [comment]
First of all I want to rewrite my JS library on Swift (https://github.com/makleso6/homebridge-broadlink-heater-cooler)
I think tagging related project is good idea:) Thanks!
