### ISSUE TITLE
How to add HAP as a dependency in Swift Package Manager?

### ISSUE THREAD

**Issue by zeusent** [Bouke/HAP#94]
I'm new to this and the Readme file doesn't really show. Could you explain how I'm supposed to add HAP as a library to my dependencies list in Swift's Package Manager? Maybe add the instructions to the Readme for other people that are as noob as I am? :)

Thanks!

**Comment by Bouke** [comment]
I guess you should get started with learning [how to use Swift Package Manager](https://www.google.com/search?hl=en&q=how%20to%20use%20swift%20package%20manager). There's pretty good content out there that should you get started.
